databases:
  - name: bracket-postgres
    plan: free

services:
  # Backend: FastAPI via Docker
  - type: web
    name: bracket-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    plan: starter
    healthCheckPath: /ping
    envVars:
      - key: ENVIRONMENT
        value: PRODUCTION
      - key: PG_DSN
        fromDatabase:
          name: bracket-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@bnsports
      - key: ADMIN_PASSWORD
        value: Auv3oH3v_5kD2QmF7wE9pVwY8tZs
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: bracket-frontend
          property: hostport

  # Frontend: Next.js SSR served by Render as a Node web service
  - type: web
    name: bracket-frontend
    env: node
    rootDir: frontend
    buildCommand: yarn install --network-timeout 1000000 && yarn build
    startCommand: yarn start
    autoDeploy: true
    plan: starter
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://bracket-backend-latest.onrender.com
      - key: NEXT_PUBLIC_HCAPTCHA_SITE_KEY
        value: 10000000-ffff-ffff-ffff-000000000001
