# Render Blueprint: deploy Bracket backend (FastAPI) + frontend (Next.js) + Postgres

databases:
  - name: bracket-postgres
    plan: free

services:
  - type: web
    name: bracket-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    plan: starter
    healthCheckPath: /ping
    envVars:
      - key: ENVIRONMENT
        value: PRODUCTION
      - key: PG_DSN
        fromDatabase:
          name: bracket-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@bnsports
      - key: ADMIN_PASSWORD
        value: Auv3oH3v_5kD2QmF7wE9pVwY8tZs
      - key: BASE_URL
        fromService:
          type: web
          name: bracket-backend
          property: hostport
      - key: CORS_ORIGINS
        fromService:
          type: static
          name: bracket-frontend
          property: hostport

  - type: static
    name: bracket-frontend
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run export
    publishPath: frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: bracket-backend
          property: hostport
      - key: NEXT_PUBLIC_HCAPTCHA_SITE_KEY
        value: 10000000-ffff-ffff-ffff-000000000001
